config/routes.rb
Rails.application.routes.draw do
  resource :auth_token, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy, :update]
  resources :posts, except: [:new, :edit]
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post

  validates :body, presence: true, length: { minimum: 10, maximum: 1000 }
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :body, :title, :author, presence: true
  validates :title, uniqueness: true
  validates :body, length: { minimum: 20 }

  has_many :comments, dependent: :destroy
  belongs_to :author, class_name: User
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_secure_token :auth_token

  validates :username, :password_digest, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include JumpIn::Authentication

  before_action :authenticate_by_auth_token, only: [:create, :destroy, :update]

  # this app is API only, do not verify csrf token
  protect_from_forgery with: :null_session

  private

  attr_reader :current_user # override `jump_in` variation that uses session/cookies

  def authenticate_by_auth_token
    auth_token = request.headers['HTTP_X_TOKEN'].presence
    user       = auth_token && User.find_by(auth_token: auth_token)

    if user
      @current_user = user
    else
      render nothing: true, status: 401
    end
  end
end

app/controllers/auth_tokens_controller.rb
class AuthTokensController < ApplicationController
  skip_before_action :authenticate_by_auth_token

  respond_to :json

  def create
    user = User.find_by!(username: params[:username])

    if authenticate_by_strategy(user: user, params: params)
      respond_with user, location: nil
    else
      render nothing: true, status: 401
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  respond_to :json

  def index
    @comments = Comment.all

    respond_with @comments
  end

  def show
    respond_with @comment
  end

  def new
    @comment = Comment.new
    respond_with @comment
  end

  def edit
    respond_with @comment
  end

  def create
    @comment = Comment.create(comment_params)
    respond_with @comment
  end

  def update
    @comment.update(comment_params)
    respond_with @comment
  end

  def destroy
    @comment.destroy
    respond_with @comment
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:body, :post_id, :nickname)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :update, :destroy]

  respond_to :json

  def index
    @posts = Post.includes(:comments)
    respond_with @posts, include: ['comments']
  end

  def show
    respond_with @post, include: ['comments']
  end

  def new
    @post = Post.new
    respond_with @post
  end

  def edit
    respond_with @post
  end

  def create
    @post = Post.create(post_params)
    respond_with @post
  end

  def update
    @post.update(post_params)
    respond_with @post
  end

  def destroy
    @post.destroy
    respond_with @post
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:data).require(:attributes).permit(:title, :body, :author_id)
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :authenticate_by_auth_token, only: [:show_current]

  respond_to :json

  def show_current
    respond_with current_user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_by_auth_token, only: [:show_current]

  respond_to :json

  def show_current
    respond_with current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sign_in_helper.rb
module SignInHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :post_id %><br>
    <%= f.text_field :post_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>Post</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.body %></td>
        <td><%= comment.post %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>Post:</strong>
  <%= @comment.post %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EmberjsBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>